spring:
 datasource:
  url: jdbc:postgresql://${DB_HOST:localhost}:5432/dbrpe
  username: user
  password: password
 jpa:
  properties:
    hibernate:
     dialect: org.hibernate.dialect.PostgreSQL82Dialect