server:
 port: ${SERVER_PORT:9101}

spring:
 datasource:
  url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/dbrpe
  username: user
  password: password
 jpa:
  properties:
    hibernate:
     dialect: org.hibernate.dialect.PostgreSQL82Dialect