version: "3.8"

services:
  ms-rpe-product:
    build:
      context: ./ms-rpe-product
      dockerfile: Dockerfile
    ports:
      - "9101:9101"
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: postgres 
      DB_PORT: 5432
    networks:
      - app-network
      
  ms-rpe-client:
    build:
      context: ./ms-rpe-client
      dockerfile: Dockerfile
    ports:
      - "9102:9102"
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: postgres 
      DB_PORT: 5432
      CARDS_URL: http://localhost:9103/cards
      SQS_ENDPOINT: http://localstack:4566
      SQS_QUEUE_URI: http://localstack:4566/000000000000/queue-card
    depends_on:
      - localstack
    networks:
      - app-network
  ms-rpe-card:
    build:
      context: ./ms-rpe-card
      dockerfile: Dockerfile
    ports:
      - "9103:9103"
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: postgres 
      DB_PORT: 5432
      PRODUCTS_URL: http://localhost:9101/products
      SQS_ENDPOINT: http://localstack:4566
      SQS_QUEUE_URI: http://localstack:4566/000000000000/queue-card
    depends_on:
      - localstack
    networks:
      - app-network
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbrpe
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-container
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network
  redis:
    image: "redis:alpine"
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network
  aws-cli:
    image: amazon/aws-cli:latest
    container_name: aws-cli-container
    entrypoint: ["/bin/sh", "-c", "until aws --endpoint-url=http://localstack-container:4566 sqs create-queue --queue-name queue-card; do sleep 2; done"]
    environment:
      - AWS_ACCESS_KEY_ID=accessKey
      - AWS_SECRET_ACCESS_KEY=secretKey
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - localstack
    networks:
      - app-network
networks:
  app-network:
    driver: bridge